name: walkie_talkie_webrtc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_auth: ^4.17.6
  firebase_core: ^2.22.0
  firebase_database: ^10.4.7
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.48+hotfix.1
  sdp_transform: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
