// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXeYQV-itqu3vhR3XIAVLVKuMfOye8Bc',
    appId: '1:426570247106:android:aaae9f832f3030f97d445b',
    messagingSenderId: '426570247106',
    projectId: 'walkie-talkie-webrtc',
    databaseURL: 'https://walkie-talkie-webrtc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'walkie-talkie-webrtc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Njjvmt-HNYQivx_lN7ZxSaBzCqMAHLA',
    appId: '1:426570247106:ios:90d83fbdc495f2727d445b',
    messagingSenderId: '426570247106',
    projectId: 'walkie-talkie-webrtc',
    databaseURL: 'https://walkie-talkie-webrtc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'walkie-talkie-webrtc.appspot.com',
    iosBundleId: 'com.example.walkieTalkieWebrtc',
  );
}
